routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// rutas con el prefijo ventas     /ventas/...
Route::prefix('ventas')->group(function () {

    // visualizar todas las ventas
    Route::get('/', function () {
        return view('ventas.table-ventas');
    });

});

// rutas resources para los diferentes modulos
Route::resource('ventas', 'VentasController');

Route::resource('productos', 'ProductosController');

Route::resource('clientes', 'ClientesController');

// rutas para eliminar elementos desde el boton

Route::get('clientes/{id}/destroy', 
    [
        'uses' => 'ClientesController@destroy',
        'as'   => 'clientes.destroy'
    ]);

Route::get('productos/{id}/destroy', 
    [
        'uses' => 'ProductosController@destroy',
        'as'   => 'productos.destroy'
    ]);

Route::get('ventas/{id}/destroy', 
    [
        'uses' => 'VentasController@destroy',
        'as'   => 'ventas.destroy'
    ]);

app/Models/Venta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Venta extends Model
{
    protected $primaryKey = ['factura_numero', 'producto_codigo'];

    protected $fillable = ['factura_numero', 'producto_codigo', 'cantidad'];

    public $timestamps = false;

    public function pruductos()
    {
        return $this->belongsTo('App\Models\Producto');
    }

    public function facturas()
    {
        return $this->belongsTo('App\Models\Factura');
    }
}

app/Http/Controllers/VentasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Venta;
use App\Models\Cliente;
use App\Models\Factura;

class VentasController extends Controller
{
    
    public function index()
    {
        /*se obtienen todos los datos de las ventas pertenecientes
        a las distintas facturas*/
        $ventas=DB::table('ventas')
            ->join('facturas', 'ventas.factura_numero', '=', 'facturas.numero')
            ->join('clientes', 'facturas.cliente_cedula', '=', 'clientes.cedula')
            ->join('productos', 'ventas.producto_codigo', '=', 'productos.codigo')
            ->join('precios', 'productos.codigo', '=', 'precios.producto_codigo')
            ->select('ventas.factura_numero', 'productos.codigo', 'facturas.fecha', 'clientes.cedula', 'clientes.razon_social', 'precios.precio', 'ventas.cantidad')
            ->whereRaw('facturas.fecha >= precios.desde')
            ->where(function ($query) {
                $query->whereRaw('facturas.fecha <= precios.hasta')
                    ->orWhereRaw("precios.status =  'activo'");
            })
            ->get();
        
    
        /*Luego se recorre cada venta para obtener los datos
            necesarios para crear las facturas,
            almacenandolos en un arreglo*/
        /*Se inicializa una variable como punto de comparacion
        entre las facturas..*/
        /*Teniendo en cuenta que cada dato en la tabla ventas,
        representa el producto y la cantidad vendida para 
        ese producto en la factura */
        $fact=0;

        foreach ($ventas as $venta) {
            /* Si el numero de factura es diferente al numero
            de factura guardado anteriormente creamos otra factura..*/
            if ($venta->factura_numero!=$fact) {
                /*si es la primera factura que crearemos inicializamos
                el contador del arreglo de las facturas en 0 */
                if ($fact==0) {
                    $i=0;
                }
                else{
                    /* sino calculamos el iva y el total de la factura
                    lo almacenamos y aumentamos el contador para crear
                    la otra factura...*/
                    $factura[$i]['iva']=$factura[$i]['subtotal'] * 0.12;
                    $factura[$i]['total']=$factura[$i]['subtotal'] + $factura[$i]['iva'];
                    $i++;
                }
                /*creamos la factura nueva*/
                
                $subtotal= $venta->precio * $venta->cantidad;
                $iva= $subtotal * 0.12;
                $total= $subtotal + $iva;

                /*arreglo para las facturas*/
                $factura[$i]=[
                    'numero'        =>  $venta->factura_numero,
                    'cedula'        =>  $venta->cedula,
                    'razon_social'  =>  $venta->razon_social,
                    'fecha'         =>  $venta->fecha,
                    'subtotal'      =>  $subtotal,
                    'iva'           =>  $iva,
                    'total'         =>  $total,
                ];

                $fact=$venta->factura_numero;
            }
            else{
                /*Si la venta pertenece a la misma factura,
                    aumentamos el subtotal, iva y total de la factura.*/
                $sub=$venta->precio * $venta->cantidad;
                
                $factura[$i]['subtotal'] = $factura[$i]['subtotal'] + $sub;
                $factura[$i]['iva']= $factura[$i]['subtotal'] * 0.12;
                $factura[$i]['total']= $factura[$i]['subtotal'] + $factura[$i]['iva'];
            }
        }

        return view('ventas.table-ventas', ['facturas' => $factura]);
    }

    
    public function create()
    {   
        // Seleccion de todos los clientes
        $clientes= Cliente::all();

        /* Adicional se seleccionan los productos con sus precios
        para enviarlos al formulario de realizar una nueva venta.*/

        $productos = DB::table('productos')
            ->join('precios', 'productos.codigo', '=', 'precios.producto_codigo')
            ->select('productos.codigo', 'productos.nombre', 'productos.cantidad', 'precios.precio')
            ->where('precios.status', '=', 'activo')
            ->where('productos.cantidad', '>', 0)
            ->get();
            
        // retornamos a la vista y enviamos los datos
        return view('ventas.form-ventas', ['clientes' => $clientes, 'productos' => $productos]);
    }


    public function store(Request $request)
    {
        /* se validan los datos requeridos*/
        $request->validate([
            'cliente' => 'required',
            'productos' => 'required',
        ]);

        $datos = $request->all();

        $factura=[
                    'fecha' => now(),
                    'cliente_cedula' => $datos['cliente']
        ];

        $productos= $datos['productos'];
        $cantidad=  $datos['cantidad'];
        /* se valida que la cantidad de los productos
        seleccionados sean mayores que 0.
        Si lo es se retorna al formulario */
        foreach ($productos as $producto) {

            if ( $cantidad[$producto] <= 0 ) {
                flash('La cantidad del producto '.$producto.' no puede ser igual o menor a 0.')->error();
                return back()->withInput();
            }

        }
        /* se registra la nueva factura */
        if (Factura::create($factura)) {
            /* se selcciona el codigo de la factura 
            que se acaba de registrar*/
            $fact=DB::table('facturas')
                ->where("fecha", "=", $factura['fecha'])
                ->where("cliente_cedula", "=", $factura['cliente_cedula'])
                ->get();

            for ($i=0; $i < count($productos); $i++) 
            {
                /*se cargan todas las ventas pertenecientes
                a la factura nueva*/
                DB::table('ventas')->insert(
                    ['factura_numero' => $fact[0]->numero, 'producto_codigo'=> $productos[$i], 'cantidad'=>(int)$cantidad[$productos[$i]] ]
                );
                /* Se disminuye la cantidad de los productos en existencia */
                DB::table('productos')->where('codigo', $productos[$i])->decrement('cantidad', (int)$cantidad[$productos[$i]]);
            }

            // alerta a mostrar si la operacion es exitosa
            return redirect()->route('ventas.show',['numero' => $fact[0]->numero]);
        }

    }

   
    public function show($id)
    {
        /* se obtienen todas las ventas pertenecientes a la factura
        indicada con el fin de armar la vista de factura.*/
        $ventas=DB::table('ventas')
            ->join('facturas', 'ventas.factura_numero', '=', 'facturas.numero')
            ->join('clientes', 'facturas.cliente_cedula', '=', 'clientes.cedula')
            ->join('productos', 'ventas.producto_codigo', '=', 'productos.codigo')
            ->join('precios', 'productos.codigo', '=', 'precios.producto_codigo')
            ->select('ventas.factura_numero',  'facturas.fecha', 'clientes.cedula', 'clientes.razon_social', 'clientes.telefono','clientes.direccion', 'productos.codigo', 'productos.nombre','precios.precio as precio_unitario', 'ventas.cantidad', DB::raw('precios.precio * ventas.cantidad as precio'), DB::raw('(precios.precio * ventas.cantidad) * 0.12 as iva') )
            ->where('ventas.factura_numero', '=', $id)
            ->whereRaw('facturas.fecha >= precios.desde')
            ->where(function ($query) {
                $query->whereRaw('facturas.fecha <= precios.hasta')
                    ->orWhereRaw("precios.status =  'activo'");
            })
            ->get();
        /* Variables para calcular el subtotal y el iva*/
        $subtotal= 0;
        $iva= 0;
        /*Se calcula el subtotal y el iva*/
        foreach ($ventas as $venta) {
            
            $subtotal= $subtotal + $venta->precio;
            $iva= $iva + $venta->iva;

        }

        $total= $subtotal + $iva;
        // se muestra la factura.
        return view('ventas.factura', ['ventas' => $ventas, 'subtotal' => $subtotal, 'iva' => $iva, 'total' => $total]);
    }

   
    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/ventas/factura.blade.php
@extends('layouts.main')

@section('title','Ventas')
<!-- titulo en el contenido -->
@section('tit')
  <h2>Factura</h2>
@endsection

@section('content')
	
	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="margin-bottom: 20px">
		
		<tr>
			<th colspan="5" class="mdl-data-table__cell--non-numeric">
				Factura {{ $ventas[0]->factura_numero }}
			</th>
		</tr>

		<tr>
			<th colspan="5" class="mdl-data-table__cell--non-numeric">
				{{ date('d-m-Y',strtotime($ventas[0]->fecha)) }}
			</th>
		</tr>
		<tr>
			<th colspan="5" class="mdl-data-table__cell--non-numeric">
				{{ date('H:i:s',strtotime($ventas[0]->fecha)) }}
			</th>
		</tr>

		<tr>
			<th colspan="5" class="mdl-data-table__cell--non-numeric">
				Datos del Cliente:
			</th>
		</tr>
		<tr>
			<td colspan="5" class="mdl-data-table__cell--non-numeric" style="border:0px">
				Cedula: {{ $ventas[0]->cedula }}
			</td>
		</tr>
		<tr>
			<td colspan="5" class="mdl-data-table__cell--non-numeric" style="border:0px">
				Razon Social: {{ $ventas[0]->razon_social }}
			</td>
		</tr>
		<tr>
			<td colspan="5" class="mdl-data-table__cell--non-numeric" style="border:0px">
				Telefono: {{ $ventas[0]->telefono }}
			</td>
		</tr>
		<tr>
			<td colspan="5" class="mdl-data-table__cell--non-numeric" style="border:0px">
				Direccion: {{ $ventas[0]->direccion }}
			</td>
		</tr>

		<tr>
			<th class="mdl-data-table__cell--non-numeric">Codigo</th>
			<th class="mdl-data-table__cell--non-numeric">Producto</th>
			<th>Cantidad</th>
			<th>Precio Unitario</th>
			<th>Precio</th>
		</tr>
		<!-- se muestran todos los productos -->
		@foreach($ventas as $venta)
			<tr>
				<td class="mdl-data-table__cell--non-numeric">{{ $venta->codigo }}</td>
				<td class="mdl-data-table__cell--non-numeric">{{ $venta->nombre }}</td>
				<td>{{ $venta->cantidad }}</td>
				<td>{{ number_format($venta->precio_unitario, 2, ',','.') }}</td>
				<td>{{ number_format($venta->precio, 2, ',','.') }}</td>
			</tr>
		@endforeach

		<tr>
			<th colspan="4">Sub-Total</th>
			<th> {{ number_format($subtotal, 2, ',','.') }}</th>
		</tr>

		<tr>
			<th colspan="4">Iva</th>
			<th> {{ number_format($iva, 2, ',','.') }}</th>
		</tr>

		<tr>
			<th colspan="4">Total General</th>
			<th> {{ number_format($total, 2, ',','.') }}</th>
		</tr>
	</table>

@endsection

resources/views/ventas/form-ventas.blade.php
<!-- extendemos a la plantilla principal donde se encuentra el menu-->
@extends('layouts.main')

<!-- titulo de la pagina -->
@section('title','Home')

<!-- titulo en el contenido -->
@section('tit')
  <h2>Registrar Venta</h2>
@endsection

<!-- seccion para mostrar errores de validacion de formularios -->
@section('errors')
 @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
@endsection

<!-- contenido -->
@section('content')
  
<div>
  <!-- divs contenedores de la barra de tabs y enlaces -->
  <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
  <div class="mdl-tabs__tab-bar">
    <a href="#tab1" class="mdl-tabs__tab">Cliente</a>
    <a href="#tab2" class="mdl-tabs__tab">Productos</a>
  </div>
  <!-- formulario divido en partes utilizando tabs-->
  <form action="{{ route('ventas.store') }}" method="POST">
    <!-- enviar el metodo para definir que ruta usar -->
    <input type="hidden" name="_method" value="POST">
    <!-- enviado el token al backend -->
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <!-- creamos un contador -->
    <!-- seccion para seleccionar el cliente -->
    <div class="mdl-tabs__panel is-active" id="tab1">
      @foreach($clientes as $cliente)
        <div class="mdl-textfield">
          <label class = "mdl-radio mdl-js-radio">
            <input type="radio" name="cliente" class = "mdl-radio__button" value="{{$cliente['cedula']}}" required>
             <span class="mdl-radio__label">
              {{ "Cedula: ".$cliente['cedula'] }}
              <br>
              {{ "Razon Social: ".$cliente['razon-social'] }}
            </span>
          </label>
        </div>
        <br>
      @endforeach
    </div>
    <!-- seccion para seleccionar los productos a vender -->
    <div class="mdl-tabs__panel" id="tab2">
      <!-- si hay productos disponibles -->
      @if(count($productos) > 0)
      <!-- se muestran todos los productos -->
        @foreach($productos as $producto)
        <!-- Si el producto no tiene existencia no lo mostramos -->
          @if($producto->cantidad > 0)
            <div class="mdl-textfield">
              <label class = "mdl-checkbox mdl-js-checkbox">
              <input type="checkbox" class="mdl-checkbox__input" name="productos[]" value="{{$producto->codigo}}">
              <span class = "mdl-checkbox__label">
              {{"Nombre: ".$producto->nombre}}<br>
              {{"Precio: ".number_format($producto->precio, 2 , ",",".")."bs."}}<br>
              </span>
              </label>

            </div>
            <br>
            <div class="mdl-textfield">
              {{"Cantidad: "}} <input type="number" name="cantidad[{{$producto->codigo}}]" min="1" max="{{ $producto->cantidad }}" ><br>
            </div>
            <br>
          @endif

        @endforeach
        <br>
        <button type="submit" value="facturar" class="mdl-button mdl-js-button mdl-button--raised" name="accion">Facturar</button>
        @else
          <br>
            No hay productos en existencia.
      @endif
      
    </div>

  </form>

</div>

@endsection

resources/views/ventas/table-ventas.blade.php
@extends('layouts.main')

@section('title','Ventas')
<!-- titulo en el contenido -->
@section('tit')
  <h2>Ventas</h2>
@endsection

@section('agregar')
  <div style="float: right; margin-bottom: 20px;">
    <a href="{{ route('ventas.create')}} ">
      <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
      <i class="material-icons">add</i>  
      </button>
    </a>
  </div>
@endsection

@section('content')

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="margin-bottom: 2rem">
  <thead>
    <tr>
      <th>Factura</th>
      <th class="mdl-data-table__cell--non-numeric">Cedula</th>
      <th class="mdl-data-table__cell--non-numeric">Razon Social</th>
      <th class="mdl-data-table__cell--non-numeric">Fecha</th>
      <th>Sub. Total</th>
      <th>IVA</th>
      <th>Total</th>
      <th class="mdl-data-table__cell--non-numeric">Accion</th>
    </tr>
  </thead>
  <tbody>
     @if($facturas != '')
      @foreach($facturas as $factura )
      <tr>
        <td>{{ $factura['numero'] }}</td>
        <td>{{ $factura['cedula'] }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ $factura['razon_social'] }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ date('d-m-Y H:i:s',strtotime($factura['fecha'])) }}</td>
        <td>{{ number_format($factura['subtotal'], 2, ',', '.') }}</td>
        <td>{{ number_format($factura['iva'], 2, ',', '.') }}</td>
        <td>{{ number_format($factura['total'], 2, ',', '.') }}</td>
        <td class="mdl-data-table__cell--non-numeric">
          <a href="{{ route('ventas.show', $factura['numero']) }}">
            <button class="mdl-button mdl-js-button mdl-button--icon">
              <i class="material-icons">remove_red_eye</i>
            </button>
          </a>
        </td>

      </tr>
      @endforeach
    @endif
  </tbody>
</table>
@endsection