routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// rutas con el prefijo ventas     /ventas/...
Route::prefix('ventas')->group(function () {

    // visualizar todas las ventas
    Route::get('/', function () {
        return view('ventas.table-ventas');
    });

});

// rutas resources para los diferentes modulos
Route::resource('ventas', 'VentasController');

Route::resource('productos', 'ProductosController');

Route::resource('clientes', 'ClientesController');

// rutas para eliminar elementos desde el boton

Route::get('clientes/{id}/destroy', 
    [
        'uses' => 'ClientesController@destroy',
        'as'   => 'clientes.destroy'
    ]);

Route::get('productos/{id}/destroy', 
    [
        'uses' => 'ProductosController@destroy',
        'as'   => 'productos.destroy'
    ]);

Route::get('ventas/{id}/destroy', 
    [
        'uses' => 'VentasController@destroy',
        'as'   => 'ventas.destroy'
    ]);

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    //Primary key modificada
    protected $primaryKey = "cedula";

    protected $fillable = ['cedula', 'razon_social', 'telefono', 'direccion'];

    public function facturas()
    {
    	return $this->hasMany('App\Models\Factura');
    }
}

app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Cliente;

class ClientesController extends Controller
{
    
    public function index()
    {
        /* se obtienen los datos y se retorna a la vista
        donde se muestran todos los clientes.*/
        $clientes= Cliente::all();
        return view('clientes.table-clientes', ['clientes' => $clientes]);
    }

   
    public function create()
    {
        // retorna al formulario para agregar nuevos clientes
        return view('clientes.form-cliente');
    }

  
    public function store(Request $request)
    {
        // validacion de los datos del formulario con request

        $request->validate([
            'cedula' => 'required|max:8|unique:clientes',
            'razon_social' => 'required|max:100',
            'telefono' => 'required|min:12|max:12',
            'direccion' => 'required',
        ]);

        $datos=$request->all();
        // se organizan los datos para el uso de eloquent
        $cliente= [
                    "cedula"    =>  $datos['cedula'],
                    "razon_social"  =>  $datos['razon_social'],
                    "telefono"     =>  $datos['telefono'],
                    "direccion"     =>  $datos['direccion']

        ];
        // se crea el nuevo cliente
        if (Cliente::create($cliente))
        {   
            // alerta a mostrar si la operacion es exitosa
            flash('Registro realizado')->success();
            return redirect('clientes');
        }
        // alerta a mostrar si la operacion falla
        flash('Ocurrio un error inesperado en el registro')->error();
        return redirect('clientes');
    }

    public function edit($cedula)
    {
        /*Se busca la informacion del cliente solicitado
        y se retorna a la vista para modificarlo*/
        $cliente=Cliente::find($cedula);
       
        return view('clientes.edit-cliente', ['cliente' => $cliente->toArray()]);
    }

    
    public function update(Request $request, $cedula)
    {
        //validacion de datos con request
        /*Si la cedula del cliente no se modifico
            no es necesario aplicar el valor unique*/
        if ($cedula == $request->cedula) {
            $request->validate([
                'cedula' => 'required|max:8',
                'razon_social' => 'required|max:100',
                'telefono' => 'required|min:12|max:12',
                'direccion' => 'required',
              ]);
        }
        else{
            /*Si la cedula se modifico verificamos que
            no sea igual a otro existente*/
            $request->validate([
                'cedula' => 'required|max:8|unique:clientes',
                'razon_social' => 'required|max:100',
                'telefono' => 'required|min:12|max:12',
                'direccion' => 'required',
            ]);
        }
       
        
        $datos=$request->all();
        // actualizamos los datos del cliente en la base de datos
        $cliente=Cliente::where('cedula', $cedula)
                    ->update([
                        'cedula' => $datos['cedula'], 
                        'razon_social'  =>  $datos['razon_social'], 
                        'telefono'     =>  $datos['telefono'], 
                        'direccion'     =>  $datos['direccion']
                        ]);
        //Verificamos si se hizo la actualizacion
        if($cliente)
        {
            // alerta a mostrar si la operacion es exitosa
            flash('Modificacion realizada')->success();
            return redirect('clientes');
        }
        // alerta a mostrar si la operacion falla
        flash('Ocurrio un error inesperado en la modificacion')->error();
        return redirect('clientes');
    }

  
    public function destroy($cedula)
    {
        //Buscamos el cliente
        $cliente=Cliente::find($cedula);
        /*Ejecutamos la funcion de eliminar 
        de eloquent para el cliente seleccionado*/
        if($cliente->delete())
        {
            // alerta a mostrar si la operacion es exitosa
            flash('Cliente eliminado')->success();
            return redirect('clientes');
        }
        // alerta a mostrar si la operacion falla
        flash('Ocurrio un error inesperado en la eliminacion')->error();
        return redirect('clientes');
    }
}

resources/views/clientes/edit-cliente.blade.php
<!-- extendemos a la plantilla principal donde se encuentra el menu-->
@extends('layouts.main')

<!-- titulo de la pagina -->
@section('title','Editar Cliente')

<!-- titulo en el contenido -->
@section('tit')
  <h2>Editar Cliente</h2>
@endsection

<!-- seccion para mostrar errores de validacion de formularios -->
@section('errors')
 @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
@endsection

@section('content')
<form action="{{ route('clientes.update', $cliente['cedula'] ) }}" method="POST">

    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="cedula" name="cedula" value="{{ $cliente['cedula'] }}">
        <label class="mdl-textfield__label" for="cedula">Cedula</label>
        <span class="mdl-textfield__error">El dato no es un numero!</span>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="rz-social" name="razon_social" value="{{ $cliente['razon_social'] }}">
        <label class="mdl-textfield__label" for="rz-social">Razon Social</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="telefono" name="telefono" value="{{ $cliente['telefono'] }}">
        <label class="mdl-textfield__label" for="telefono">Telefono</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <textarea class="mdl-textfield__input" type="text" rows="1" id="direccion" name="direccion">{{ $cliente['direccion'] }}</textarea>
        <label class="mdl-textfield__label" for="direccion">Direccion</label>
    </div>
    <br>

    <button type="submit" value="Modificar" class="mdl-button mdl-js-button mdl-button--raised" name="Modificar">Modificar</button>
    
</form>
@endsection

resources/views/clientes/form-cliente.blade.php
<!-- extendemos a la plantilla principal donde se encuentra el menu-->
@extends('layouts.main')

<!-- titulo de la pagina -->
@section('title','Home')

<!-- titulo en el contenido -->
@section('tit')
  <h2>Registrar Cliente</h2>
@endsection

<!-- seccion para mostrar errores de validacion de formularios -->
@section('errors')
 @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
@endsection

<!-- contenido -->
@section('content')
 <!-- formulario para crear clientes con la ruta clientes.store definida en la ruta resources -->
 
<form action="{{ route('clientes.store') }}" method="POST">
    <input type="hidden" name="_method" value="POST">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="cedula" name="cedula">
        <label class="mdl-textfield__label" for="cedula">Cedula</label>
        <span class="mdl-textfield__error">El dato no es un numero!</span>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="razon_social" name="razon_social">
        <label class="mdl-textfield__label" for="razon_social">Razon Social</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="telefono" name="telefono">
        <label class="mdl-textfield__label" for="telefono">Telefono</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <textarea class="mdl-textfield__input" type="text" rows="1" id="direccion" name="direccion"></textarea>
        <label class="mdl-textfield__label" for="direccion">Direccion</label>
    </div>
    <br>

    <button type="submit" value="Registrar" class="mdl-button mdl-js-button mdl-button--raised" name="Registrar">Registrar</button>

</form>
@endsection

resources/views/clientes/table-clientes.blade.php
@extends('layouts.main')

@section('title','Clientes')

<!-- titulo en el contenido -->
@section('tit')
  <h2>Clientes</h2>
@endsection

@section('agregar')
<div style="float: right; margin-bottom: 20px;">
  <a href="{{ route('clientes.create')}} ">
    <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
    <i class="material-icons">add</i>  
    </button>
  </a>
</div>
@endsection

@section('content')

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
  <thead>
    <tr>
      <th>Cedula</th>
      <th class="mdl-data-table__cell--non-numeric">Razon Social</th>
      <th class="mdl-data-table__cell--non-numeric">Direccion</th>
      <th class="mdl-data-table__cell--non-numeric">Telefono</th>
      <th class="mdl-data-table__cell--non-numeric">Accion</th>
    </tr>
  </thead>
  <tbody>
    <!-- si la tabla clientes no esta vacia hacemos un recorrido
        y mostramos todos los datos -->
    @if($clientes != '')
      @foreach($clientes as $cliente )
      <tr>
        <td>{{ $cliente['cedula'] }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ $cliente['razon_social'] }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ $cliente['direccion'] }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ $cliente['telefono'] }}</td>
        <td class="mdl-data-table__cell--non-numeric">
          <a href="clientes/{{ $cliente['cedula'] }}/edit">
            <button class="mdl-button mdl-js-button mdl-button--icon">
              <i class="material-icons">mode_edit</i>
            </button>
          </a>
          
            <a href="{{ route('clientes.destroy', $cliente['cedula']) }}">
              <button class="mdl-button mdl-js-button mdl-button--icon">
                <i class="material-icons">delete</i>
              </button>
          </a>
        </td>

      </tr>
      @endforeach
    @endif
    
  </tbody>
</table>
@endsection