routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// rutas con el prefijo ventas     /ventas/...
Route::prefix('ventas')->group(function () {

    // visualizar todas las ventas
    Route::get('/', function () {
        return view('ventas.table-ventas');
    });

});

// rutas resources para los diferentes modulos
Route::resource('ventas', 'VentasController');

Route::resource('productos', 'ProductosController');

Route::resource('clientes', 'ClientesController');

// rutas para eliminar elementos desde el boton

Route::get('clientes/{id}/destroy', 
    [
        'uses' => 'ClientesController@destroy',
        'as'   => 'clientes.destroy'
    ]);

Route::get('productos/{id}/destroy', 
    [
        'uses' => 'ProductosController@destroy',
        'as'   => 'productos.destroy'
    ]);

Route::get('ventas/{id}/destroy', 
    [
        'uses' => 'VentasController@destroy',
        'as'   => 'ventas.destroy'
    ]);

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    //
    protected $primaryKey = "codigo";

    protected $fillable = ['codigo', 'nombre', 'cantidad'];

    public function precios()
    {
    	return $this->hasMany('App\Models\Precio');
    }

    public function ventas()
    {
    	return $this->hasMany('App\Models\Venta');
    }
}

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Producto;
use App\Models\Precio;

class ProductosController extends Controller
{
  
    public function index()
    {
        /*Se realiza un join para la busqueda
        de los productos con su precio actual
        y se evnia los datos a la vista*/
        $productos = DB::table('productos')
            ->join('precios', 'productos.codigo', '=', 'precios.producto_codigo')
            ->select('productos.*', 'precios.*')
            ->where('precios.status', '=', 'activo')
            ->get();

        return view('productos.table-productos', ['productos' => $productos]);

    }

  
    public function create()
    {
        /*se retorna al formulario que permite
        el registro de nuevos productos*/
         return view('productos.form-productos');
    }

    
    public function store(Request $request)
    {
        /*validamos lo datos del formulario de registro*/
        $request->validate([
            'codigo' => 'required|max:15|unique:productos',
            'nombre' => 'required|max:25',
            'cantidad' => 'required|integer',
            'precio' => 'required|numeric',
        ]);

        $datos=$request->all();
        /*organizamos los datos del producto y sus precios*/
        $producto= [
                    'codigo' => $datos['codigo'],
                    'nombre' => $datos['nombre'],
                    'cantidad' => $datos['cantidad']
        ];

        $precio = [
                   'precio' => $datos['precio'],
                   'desde'  => now(),
                   'producto_codigo' => $datos['codigo'],
                   'status' =>  'activo', 
        ];
        /*creamos el producto nuevo con su respectivo precio*/
        if (Producto::create($producto) && Precio::create($precio))
        {   
            // alerta a mostrar si la operacion es exitosa
            flash('Registro realizado')->success();
            return redirect('productos');
        }
        // alerta a mostrar si la operacion falla
        flash('Ocurrio un error inesperado en el registro')->error();
        return redirect('productos');
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($codigo)
    {
        //
        $producto = DB::table('productos')
            ->join('precios', 'productos.codigo', '=', 'precios.producto_codigo')
            ->select('productos.*', 'precios.*')
            ->where('precios.status', '=', 'activo')
            ->where('productos.codigo', '=', $codigo)
            ->get();
       
        return view('productos.edit-productos', ['producto' => $producto->toArray()]);

    }

   
    public function update(Request $request, $codigo)
    {
    
        //validacion de datos con request
        if ($codigo == $request->codigo) {
            $request->validate([
                'codigo' => 'required|max:15',
                'nombre' => 'required|max:25',
                'cantidad' => 'required|integer',
                'precio' => 'required|numeric',
            ]);
        }
        else{
            $request->validate([
                'codigo' => 'required|max:15|unique:productos',
                'nombre' => 'required|max:25',
                'cantidad' => 'required|integer',
                'precio' => 'required|numeric',
            ]);
        }
       
        
        $datos=$request->all();
    

        $producto=Producto::where('codigo', $codigo)
                    ->update([
                        'codigo' => $datos['codigo'],
                        'nombre' => $datos['nombre'],
                        'cantidad' => $datos['cantidad']
                        ]);

        $precio=Precio::where('producto_codigo', $codigo)
                    ->where('status','activo')
                    ->update([
                        'hasta'  => now(),
                        'status' => 'inactivo'
                        ]);

        $precio = [
                   'precio' => $datos['precio'],
                   'desde'  => now(),
                   'producto_codigo' => $datos['codigo'],
                   'status' =>  'activo', 
        ];

        if($producto && Precio::create($precio))
        {
            // alerta a mostrar si la operacion es exitosa
            flash('Modificacion realizada')->success();
            return redirect('productos');
        }
        // alerta a mostrar si la operacion falla
        flash('Ocurrio un error inesperado en la modificacion')->error();
        return redirect('productos');
    }

    public function destroy($codigo)
    {
        //Buscamos el cliente
        $producto=Producto::find($codigo);
        // ejecutamos la funcion de eliminar
        if($producto->delete())
        {
            // alerta a mostrar si la operacion es exitosa
            flash('Producto eliminado')->success();
            return redirect('productos');
        }
        // alerta a mostrar si la operacion falla
        flash('Ocurrio un error inesperado en la eliminacion')->error();
        return redirect('productos');


    }
}

resources/views/productos/edit-productos.blade.php
<!-- extendemos a la plantilla principal donde se encuentra el menu-->
@extends('layouts.main')

<!-- titulo de la pagina -->
@section('title','Editar producto')

<!-- titulo en el contenido -->
@section('tit')
  <h2>Editar producto</h2>
@endsection

<!-- seccion para mostrar errores de validacion de formularios -->
@section('errors')
 @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
@endsection

<!-- contenido -->
@section('content')
 <!-- formulario para edicion de productos-->

<form action="{{ route('productos.update', $producto[0]->codigo) }}" method="POST">
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="codigo" name="codigo" value="{{ $producto[0]->codigo }}">
        <label class="mdl-textfield__label" for="codigo">Codigo</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="nombre" name="nombre" value="{{ $producto[0]->nombre }}">
        <label class="mdl-textfield__label" for="nombre">Nombre</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="cantidad" name="cantidad" value="{{ $producto[0]->cantidad }}">
        <label class="mdl-textfield__label" for="cantidad">Cantidad</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="precio" name="precio" value="{{ $producto[0]->precio }}">
        <label class="mdl-textfield__label" for="precio">Precio</label>
    </div>
    <br>

    <button type="submit" value="Modificar" class="mdl-button mdl-js-button mdl-button--raised" name="Modificar">Modificar</button>

</form>
@endsection

resources/views/productos/form-productos.blade.php
<!-- extendemos a la plantilla principal donde se encuentra el menu-->
@extends('layouts.main')

<!-- titulo de la pagina -->
@section('title','Agregar producto')

<!-- titulo en el contenido -->
@section('tit')
  <h2>Agregar producto</h2>
@endsection

<!-- seccion para mostrar errores de validacion de formularios -->
@section('errors')
 @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
@endsection

<!-- contenido -->
@section('content')
 <!-- formulario para crear clientes con la ruta clientes.store definida en la ruta resources -->
 
<form action="{{ route('productos.store') }}" method="POST">
    <input type="hidden" name="_method" value="POST">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="codigo" name="codigo">
        <label class="mdl-textfield__label" for="codigo">Codigo</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="nombre" name="nombre">
        <label class="mdl-textfield__label" for="nombre">Nombre</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="cantidad" name="cantidad">
        <label class="mdl-textfield__label" for="cantidad">Cantidad</label>
    </div>
    <br>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="precio" name="precio">
        <label class="mdl-textfield__label" for="precio">Precio</label>
    </div>
    <br>

    <button type="submit" value="Registrar" class="mdl-button mdl-js-button mdl-button--raised" name="Registrar">Registrar</button>

</form>
@endsection

resources/views/productos/table-productos.blade.php
@extends('layouts.main')

@section('title','Productos')
<!-- titulo en el contenido -->
@section('tit')
  <h2>Productos</h2>
@endsection

@section('agregar')
  <div style="float: right; margin-bottom: 20px;">
  <a href="{{ route('productos.create')}} ">
    <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
    <i class="material-icons">add</i>  
    </button>
  </a>
</div>
@endsection

@section('content')

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
  <thead>
    <tr>
      <th>Codigo</th>
      <th class="mdl-data-table__cell--non-numeric">Nombre</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th class="mdl-data-table__cell--non-numeric">Accion</th>
    </tr>
  </thead>
  <tbody>
    <!-- si la tabla clientes no esta vacia hacemos un recorrido
        y mostramos todos los datos -->
    @if($productos != '')
      @foreach($productos as $producto )
      <tr>
        <td>{{ $producto->codigo }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ $producto->nombre }}</td>
        <td>{{ $producto->cantidad }}</td>
        <td>{{ number_format($producto->precio, 2, ',', '.') }}</td>
        <td class="mdl-data-table__cell--non-numeric">
          <a href="productos/{{ $producto->codigo }}/edit">
            <button class="mdl-button mdl-js-button mdl-button--icon">
              <i class="material-icons">mode_edit</i>
            </button>
          </a>
          
            <a href="{{ route('productos.destroy', $producto->codigo) }}">
              <button class="mdl-button mdl-js-button mdl-button--icon">
                <i class="material-icons">delete</i>
              </button>
          </a>
        </td>

      </tr>
      @endforeach
    @endif
    
  </tbody>
</table>
@endsection